### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by Willfa10** [basedSkeleton/my-tile#1]
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: arm-linux-gnueabihf-gcc 
Build flags: 
Id flags: -c 

The output was:
No such file or directory

thats what was in the log file.

done on raspberry pi

**Comment by basedSkeleton** [comment]
> Compiling the C compiler identification source file "CMakeCCompilerId.c" failed. Compiler: arm-linux-gnueabihf-gcc Build flags: Id flags: -c
> 
> The output was: No such file or directory
> 
> thats what was in the log file.
> 
> done on raspberry pi

Download and install Minecraft: Pi - Reborn's compiling dependencies. 
https://github.com/MCPI-Revival/minecraft-pi-reborn/blob/master/docs/BUILDING.md

Currently, all you need to do is download Minecraft: Pi - Reborn's source and run the dependency install script.
```./scripts/install-dependencies.sh```
